spring.application.name=bycontractbackend
server.port=${PORT:8080}
#DONT FORGET
#IN AUTHCONTROLLER, PASS SECURE AT TRUE TO HANDLE THE SECURITY IN HTTPS
application.cookie.secure=${COOKIE_SECURE:false}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000
# Expiration en millisecondes (ici : 1 jour = 86400000 ms)
application.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
#Turn off the spring boot banner
spring.main.banner-mode=off
#Reduce logging level
logging.level.root=warn 
#When Spring detects a non-correct field, it throws an exception
spring.jackson.deserialization.fail-on-unknown-properties=true
#Folder where data will be stored
file.upload-dir=${FILE_UPLOAD_DIR:C:/Users/ALS22/Documents/bycontract/storage}
#Spring security is useless because i have integrated JWT and SecurityFilterChain
#spring.security.user.name=root
#spring.security.user.password=root
#Communication with the database
#Uncomment the line when the database will be fully OK   spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true





